#file: noinspection LongLine
httpServerPort: 0
discordClientId: DISCORD_APP_CLIENT_ID
discordClientSecret: DISCORD_APP_CLIENT_SECRET
discordAppRedirectUri: DISCORD_APP_REDIRECT_URL_MUST_BE_AN_OPTION_AVAILABLE_IN_THE_DEVELOPER_PANEL
discordOAuthUrl: DISCORD_APP_OAUTH_URL